### ISSUE TITLE
Are the presentations included somewhere?

### ISSUE THREAD

**Issue by mwolfson** [JetBrains/kotlin-workshop#14]
I see on the README, that there is a mention that there would be presentation materials.  I would love to see them, as I am considering running a community workshop.

No big deal if that content doesn't exist (but you should remove the reference to it).

**Presentations:** For the instructor to use

**Comment by svtk** [comment]
The links can be found here: https://github.com/JetBrains/kotlin-workshop/blob/master/README.md#presentations

**Comment by mwolfson** [comment]
Sorry, I didn't see those, I was looking for them inside the actual repo, not as links (thanks!)
